class WayConstant {
  static const double Radius = 5; //全局圆角大小
  static const double fontSize = 14; //全局默认字体大小
  static const double appBarHeight = 43; //导航栏高度
  static const int errorCode404 = 404; //网络请求失败ƒwƒ
  static const int errorCode420 = 420; //网络请求已取消
  static const int errorCode408 = 408; //网络连接超时
  static const int errorCode502 = 502; //网络接收超时
  static const int errorCode450 = 450; //网络发送超时
  static const String errorMessage404 = '网络请求失败'; //网络请求失败
  static const String errorMessage420 = '网络请求已取消'; //网络请求已取消
  static const String errorMessage408 = '网络连接超时'; //网络连接超时
  static const String errorMessage502 = '网络接收超时'; //网络接收超时
  static const String errorMessage450 = '网络发送超时'; //网络发送超时
  static const String errorMessage500 = '服务器错误:'; //服务器错误
  static const String errorMessageT404 = 'Failed'; //网络请求失败
  static const String errorMessageT420 = 'Cancel'; //网络请求已取消
  static const String errorMessageT408 = 'Connect Timeout'; //网络连接超时
  static const String errorMessageT502 = 'Receive Timeout'; //网络接收超时
  static const String errorMessageT450 = 'Send Timeout'; //网络发送超时
  static const String errorMessageT500 = 'Response'; //服务器错误
  static const String regExpPositive = '[+0-9.]'; //正数
  static const String regExpNegative = '[-0-9.]'; //负数
  static const String regExpPassword = '[a-zA-Z0-9.]'; //密码
  static const String regExpDecimal = '[0-9.]'; //小数
  static const String regExpLetter = '[a-zA-Z]'; //字母
  static const String regExpChinese = '[\u4e00-\u9fa5]'; //中文
  static const String regExpEmail = '[a-zA-Z0-9.@]'; //邮箱
  static const String regExpPhone = '[0-9-]'; //国内电话号
  static const String regExpMobilePhone = '[0-9]'; //国内手机号
  static const String regExpIdCard = '[0-9Xx]'; //身份证
  static const String regExpIP = '[0-9:.]'; //ip
}
